name: Snyk Prueba

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Instalar node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar snyk
        run: npm install -g snyk

      - name: Autenticarse
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Lanzar snyk
        run: snyk test
